### ISSUE TITLE
Add Github OAuth

### ISSUE THREAD

**Issue by pranjulps3** [Velle-log/hs-ui#11]
#2 Add GitHub OAuth to the UI using `angularx-social-login` module.

**Comment by Samy-33** [comment]
@Velle-log/hs-ui-ft, is there any library from github like `gapi` of google and `sdk.js` from facebook?

**Comment by Samy-33** [comment]
@Velle-log/hs-ui-ft As I couldn't find any library to assist in github oauth flow, I am thinking of following below steps:
* Setup a route (page) `http://our-ui.com/github-oauth/`, which will retrieve the tokens from github
* Open up a new window on click event which goes to *github's oauth login page*.
* Monitor the window from the parent window, when the github redirects the user to `http://out-ui.com/github-oauth/?params=xyz` with params signifying all the details github returns back.
* Read these params from parent window and close the child window on successful read.

Open to suggestions and changes.

**Comment by pranjulps3** [comment]
The library I am using has extensibility so I am trying to add GitHub to it. Will notify as I make progress.
