### ISSUE TITLE
Implement social auth login

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-ui#7]
Steps to follow:  
  * Add `href` on the login/signup icons to third party oauth handling urls.  
  * Add `redirect_uri` to the page that handles token returned from the thirdparty oauth servers.
  * After receiving the token and other required params, make a request to the API with these values and handle the storage of return on **Auth-token, refresh token and user object**.    
## UPDATE  
Using `angularx-social-login` which automatically handles the social login for `facebook` and `google` for now.

**Comment by pranjulps3** [comment]
Checking the possibility of using `angularx-social-login` module available for Angular, evaluating if its better to use the module or create one myself. It provides handling of the `Client_ID` in a convenient way. Currently native support for `Google` and `Facebook` is available, although this can be extended for other oauth applications.

**Comment by Samy-33** [comment]
Sounds great. I'll try to do a parallel study about it. Let's close it by EOD.

**Comment by pranjulps3** [comment]
Facebook OAuth is functional only on `HTTPS` sources and hence need to find an easy solution to test on local system.

**Comment by Samy-33** [comment]
> Facebook OAuth is functional only on `HTTPS` sources and hence need to find an easy solution to test on local system.

**Issue:** Loading failed for the <script> with source “http://connect.facebook.net/en_US/sdk.js”.  
**Reason**: This issue was due to using `facebook container` in `Mozilla Firefox`. It doesn't allow loading facebook's resources from outside of facebook, insta etc.  
Disabled the extension; sdk still threw some errors but worked.  
**One of the errors thrown:** `The method FB.api can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/`

**Comment by pranjulps3** [comment]
So you're getting redirected to the facebook login page? I was getting the error in `Google Chrome`.

```
Facebook Login status is only available to HTTPS pages.
```
```
The method FB.login can no longer be called from http pages. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/
```

**Comment by Samy-33** [comment]
Yes, I am getting redirected as well as getting the required token and user information back.  
**Use the app_id I shared on slack for local testing.**

**Comment by pranjulps3** [comment]
**[Update]**
The test login requires a user white-listing for developers on an app over at `developers.facebook.com` and hence you need to ask @Samy-33 to add you to the developers list and accept the same over at the developer console for Facebook.
